### ISSUE TITLE
thanks!learned a lot!

### ISSUE THREAD

**Issue by yasooknigth** [808Mak1r/GodzillaSource#6]
Provide a little supplement: Anypeople can add plugins by yourself when recompiling, but you need to confirm the JAVASSIST version. In addition, the manifest path needs to be modified. The path given by the author contains a net folder~

**Comment by linquan443** [comment]
after maven package and run java -jar target.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/formdev/flatlaf/d
emo/intellijthemes/IJThemeInfo
        at core.ApplicationContext.initUi(ApplicationContext.java:374)
        at core.ui.MainActivity.main(MainActivity.java:269)
Caused by: java.lang.ClassNotFoundException: com.formdev.flatlaf.demo.intellijth
emes.IJThemeInfo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
